# Generated by Django 5.1.1 on 2024-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tokens',
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.CharField(max_length=500),
        ),
    ]
