# Generated by Django 5.1.1 on 2024-10-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_book_tokens_alter_book_pdf_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
